#!/usr/bin/env bash
#
# scripts/secrets-pull.sh
#
# Read every /indri-studio/cloudflare/* parameter from SSM and render
# .env at the repo root. SSM is the source of record; .env is a local
# read-only cache regenerated from SSM.
#
# Usage:
#     scripts/secrets-pull.sh                  # refresh .env from SSM
#     scripts/secrets-pull.sh -h | --help      # this help

set -euo pipefail

PROFILE="${INDRI_AWS_PROFILE:-indri-terraform}"
REGION="${INDRI_AWS_REGION:-us-west-2}"
ENV_FILE="${INDRI_ENV_FILE:-.env}"

case "${1:-}" in
  -h|--help) sed -n '3,/^$/p' "$0" | sed 's|^# \{0,1\}||'; exit 0 ;;
  '') ;;
  *) echo "unknown arg: $1" >&2; exit 2 ;;
esac

if ! aws sts get-caller-identity --profile "$PROFILE" --region "$REGION" \
    >/dev/null 2>&1; then
  echo "ERR: aws creds for profile '$PROFILE' don't work." >&2
  exit 1
fi

# Pull every /indri-studio/cloudflare/* param, decrypted. AWS CLI text
# output is tab-separated <Name>\t<Value>.
PARAMS=$(aws ssm get-parameters-by-path \
    --profile "$PROFILE" --region "$REGION" \
    --path "/indri-studio/cloudflare/" --recursive --with-decryption \
    --query 'Parameters[].[Name,Value]' --output text || true)

if [[ -z "$PARAMS" ]]; then
  echo "ERR: no /indri-studio/cloudflare/* params in SSM." >&2
  echo "     Run scripts/secrets-bootstrap.sh first." >&2
  exit 1
fi

# Map SSM path → env var name. Only known keys are emitted.
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

{
  echo "# Auto-generated by scripts/secrets-pull.sh — DO NOT HAND-EDIT."
  echo "# Source of record: AWS SSM /indri-studio/cloudflare/*."
  echo "# To rotate: aws ssm put-parameter --overwrite ..., then re-run this."
  echo ""
  r2=0
  while IFS=$'\t' read -r name value; do
    case "$name" in
      */api_token)  echo "CLOUDFLARE_API_TOKEN=$value" ;;
      */account_id) echo "CLOUDFLARE_ACCOUNT_ID=$value" ;;
      */r2_access_key_id)     echo "RCLONE_CONFIG_R2_ACCESS_KEY_ID=$value";     r2=1 ;;
      */r2_secret_access_key) echo "RCLONE_CONFIG_R2_SECRET_ACCESS_KEY=$value"; r2=1 ;;
      */r2_endpoint)          echo "RCLONE_CONFIG_R2_ENDPOINT=$value";          r2=1 ;;
      *) echo "# skipped unknown key: $name" ;;
    esac
  done <<<"$PARAMS"
  # Static rclone S3 backend config — only emitted when the R2 keys are present,
  # so a non-R2 .env stays clean. Together with the three keys above they form
  # the `R2:` remote that scripts/release-upload.sh publishes /sources through.
  if [[ $r2 -eq 1 ]]; then
    echo "RCLONE_CONFIG_R2_TYPE=s3"
    echo "RCLONE_CONFIG_R2_PROVIDER=Cloudflare"
    echo "RCLONE_CONFIG_R2_REGION=auto"
  fi
} >"$TMP"

chmod 600 "$TMP"
mv "$TMP" "$ENV_FILE"
trap - EXIT

echo "Wrote $ENV_FILE from SSM ($(wc -l <"$ENV_FILE") lines)."
